/** Mirrors Purch.Application.Inventory.InventoryItemDto. */
export interface InventoryItem {
  id: string;
  name: string;
  sku: string | null;
  baseUnit: string;
  packagingUnit: string;
  packagingSize: number;
  quantityOnHand: number;
  lowStockThreshold: number | null;
  isAutoCreatedForItem: boolean;
  linkedItemId: string | null;
  isActive: boolean;
}

export interface CreateInventoryItemRequest {
  name: string;
  sku: string | null;
  baseUnit: string;
  packagingUnit: string;
  packagingSize: number;
  lowStockThreshold: number | null;
}

export interface UpdateInventoryItemRequest extends CreateInventoryItemRequest {
  isActive: boolean;
}

/** Mirrors Purch.Domain.Enums.MovementType (serialized as an integer). */
export const MovementType = {
  StockIn: 0,
  StockOut: 1,
  Consumption: 2,
  Spoiled: 3,
  Damaged: 4,
  ForReturn: 5,
  Transfer: 6,
  Adjustment: 7,
  /** System-generated by completed sales. Never offered when recording by hand. */
  Sale: 8,
} as const;
export type MovementType = (typeof MovementType)[keyof typeof MovementType];

export interface InventoryMovement {
  id: string;
  itemId: string;
  itemName: string;
  branchId: string;
  branchName: string;
  type: MovementType;
  quantity: number;
  staffUserId: string;
  staffUserName: string;
  note: string | null;
  reasonCategory: string | null;
  photoUrl: string | null;
  supplierReference: string | null;
  createdAt: string;
}

export interface RecordMovementRequest {
  itemId: string;
  branchId: string;
  type: MovementType;
  quantity: number;
  note: string | null;
  reasonCategory: string | null;
  photoUrl: string | null;
  supplierReference: string | null;
}

export interface MovementFilter {
  itemId?: string;
  branchId?: string;
  type?: MovementType;
}

export interface MovementCursor {
  before: string;
  beforeId: string;
}

export interface Supplier {
  id: string;
  name: string;
  contactInfo: string | null;
  isActive: boolean;
}

export interface CreateSupplierRequest {
  name: string;
  contactInfo: string | null;
}

/** Mirrors Purch.Domain.Enums.PurchaseOrderStatus. */
export const PurchaseOrderStatus = {
  Draft: 0,
  Sent: 1,
  PartiallyReceived: 2,
  Received: 3,
  Cancelled: 4,
} as const;
export type PurchaseOrderStatus = (typeof PurchaseOrderStatus)[keyof typeof PurchaseOrderStatus];

export interface PurchaseOrderLine {
  id: string;
  itemId: string;
  itemName: string;
  quantityOrdered: number;
  quantityReceived: number;
  expectedUnitCost: number;
}

export interface PurchaseOrder {
  id: string;
  supplierId: string;
  supplierName: string;
  branchId: string;
  branchName: string;
  status: PurchaseOrderStatus;
  sentAt: string | null;
  lines: PurchaseOrderLine[];
}

export interface CreatePurchaseOrderRequest {
  supplierId: string;
  branchId: string;
  lines: { itemId: string; quantityOrdered: number; expectedUnitCost: number }[];
}

export interface ReceivePurchaseOrderRequest {
  lines: { lineId: string; receivedQuantity: number }[];
}

/** Mirrors Purch.Domain.Enums.BranchTransferStatus. */
export const BranchTransferStatus = {
  Pending: 0,
  InTransit: 1,
  Received: 2,
  Cancelled: 3,
} as const;
export type BranchTransferStatus = (typeof BranchTransferStatus)[keyof typeof BranchTransferStatus];

export interface BranchTransfer {
  id: string;
  sourceBranchId: string;
  sourceBranchName: string;
  destinationBranchId: string;
  destinationBranchName: string;
  status: BranchTransferStatus;
  lines: { id: string; itemId: string; itemName: string; quantity: number }[];
}

export interface CreateBranchTransferRequest {
  sourceBranchId: string;
  destinationBranchId: string;
  lines: { itemId: string; quantity: number }[];
}
